development:
  adapter: redis
  url: redis://127.0.0.1:6379/1

test:
  adapter: redis
  url: redis://127.0.0.1:6379/1

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: ucas-video1_production
